plugins {
    alias pluginCatalog.plugins.node
}

maturity = 'MATURE'
maintenance = 'FULL'
description = 'HTML encoding for every supported resource.'
descriptionDe = 'HTML-Kodierung für alle unterstützten Ressourcen.'

dependencies {
    provided 'de.interactive_instruments:xtraplatform-blobs'
    provided 'de.interactive_instruments:xtraplatform-web'
    provided 'de.interactive_instruments:xtraplatform-features'
    provided project(":ogcapi-foundation")

    testProvided(testFixtures(project(":ogcapi-foundation")))
}

ext {
    generatedResourcesDir = new File(project.buildDir, 'generated/src/main/resources/')
}

/*compileJava {
    project.sourceSets.main.resources { srcDir generatedResourcesDir }
    outputs.dir(generatedResourcesDir)
}*/
project.sourceSets.main.output.dir(generatedResourcesDir)

jar {
    manifest {
        attributes('X-Web-Resource-Version': '1.1')
        attributes('X-Web-Resource': '/ogcapi-html/assets;/assets')
    }
}

node {
    version = '22.12.0'
    download = project.findProperty('downloadNode') != 'false' ?: false
    // do not declare the repository, that is not allowed outside of settings.gradle
    // it is automatically added by the settings plugin
    distBaseUrl = null
}

npmInstall {
    inputs.file("src/main/javascript/package.json")
    inputs.file("src/main/javascript/package-lock.json")
    outputs.dir("src/main/javascript/node_modules")
    outputs.cacheIf { true }
    execOverrides {
        it.workingDir = 'src/main/javascript'
    }
}

task npmBuild(type: NpmTask) {
    dependsOn npmInstall
    inputs.file("src/main/javascript/package.json")
    inputs.file("src/main/javascript/package-lock.json")
    inputs.file("src/main/javascript/vite.config.js")
    inputs.dir("src/main/javascript/vite-plugins")
    inputs.dir("src/main/javascript/src")
    outputs.dir(generatedResourcesDir)
    outputs.cacheIf { true }
    execOverrides {
        it.workingDir = 'src/main/javascript'
    }
    args = ['run', 'build']
}

task npmStart(type: NpmTask) {
    dependsOn npmInstall
    execOverrides {
        it.workingDir = 'src/main/javascript'
    }
    args = ['run', 'start']
}

task npmStorybook(type: NpmTask) {
    dependsOn npmInstall
    execOverrides {
        it.workingDir = 'src/main/javascript'
    }
    args = ['run', 'storybook']
}

processResources.dependsOn npmBuild
