/*
 * Copyright 2022 interactive instruments GmbH
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package de.ii.ogcapi.crud

import groovy.json.JsonOutput
import groovy.json.JsonSlurper
import spock.lang.IgnoreIf
import spock.lang.Requires
import spock.lang.Shared
import spock.lang.Specification

import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpRequest.BodyPublishers
import java.net.http.HttpResponse
import java.net.http.HttpResponse.BodyHandlers
import java.time.Duration

/**
 * Manual smoke specs for the CRUD GeoJSON input path. Gated on environment variables so it is
 * skipped in CI; run it locally against an ldproxy instance configured with a CRUD-enabled
 * GeoJSON format on the target collection.
 *
 * <p>The collection's {@code supportsNonAutogeneratedResourceIds} flag (read from the
 * collection metadata at setup time) decides which method creates a feature:
 * <ul>
 *   <li>{@code false} (or absent): POST to {@code /items} creates with a server-assigned id;
 *       PUT to {@code /items/{id}} only replaces an existing feature.</li>
 *   <li>{@code true}: POST is not allowed; PUT to a chosen id both creates (201) and
 *       replaces (204).</li>
 * </ul>
 * Create-side tests run only when the deployment supports the chosen mode; the replace and
 * PATCH tests always run.
 *
 * <p>Required env vars (skipped without all four):
 * <ul>
 *   <li>{@code SUT_URL} — base URL of the running ldproxy</li>
 *   <li>{@code SUT_PATH} — API path prefix (e.g. {@code /daraa})</li>
 *   <li>{@code SUT_COLLECTION} — collection id (e.g. {@code aeronauticcrv})</li>
 *   <li>{@code SUT_BODY_FILE} — path to a GeoJSON Feature file accepted by the
 *       collection's schema; used for the create/replace/round-trip cases</li>
 * </ul>
 * Optional:
 * <ul>
 *   <li>{@code SUT_ID} — feature id used for PUT-replace (defaults to the {@code id}
 *       property scraped from the body)</li>
 *   <li>{@code SUT_CONTENT_CRS} — value of a {@code Content-Crs} header attached to every
 *       body-bearing request, e.g. {@code <http://www.opengis.net/def/crs/EPSG/0/25832>}</li>
 *   <li>{@code SUT_FRESH_ID} — an id that does <em>not</em> currently exist in the
 *       collection. Enables create-side tests when the collection uses PUT-creates mode.
 *       The spec deletes the resource at this id after every iteration and again in
 *       {@code cleanupSpec}, so each create-side test starts from a clean slate and no
 *       feature is left behind.</li>
 * </ul>
 *
 * <p>Uses {@link java.net.http.HttpClient} so the spec works on Groovy 4 without pulling in
 * the (unmaintained, Groovy-2-era) http-builder dependency.
 */
@Requires({
    env['SUT_URL'] != null &&
            env['SUT_PATH'] != null &&
            env['SUT_COLLECTION'] != null &&
            env['SUT_BODY_FILE'] != null
})
class TransactionalRESTApiSpec extends Specification {

    static final String GEOJSON_CONTENT_TYPE = 'application/geo+json'

    @Shared String sutUrl = System.getenv('SUT_URL')
    @Shared String sutPath = System.getenv('SUT_PATH')
    @Shared String sutCollection = System.getenv('SUT_COLLECTION')
    @Shared String sutReplaceId = System.getenv('SUT_ID')
    @Shared String sutFreshId = System.getenv('SUT_FRESH_ID')
    @Shared String sutContentCrs = System.getenv('SUT_CONTENT_CRS')
    @Shared byte[] sutBody = loadBody(System.getenv('SUT_BODY_FILE'))

    /** True when {@code supportsNonAutogeneratedResourceIds} is {@code true} on the collection. */
    @Shared boolean putCreates = false

    HttpClient httpClient = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(10))
            .build()

    def setupSpec() {
        // Read the collection metadata once to learn which method creates a feature here. We
        // probe the collection rather than relying on env-var input so the spec self-adapts to
        // the deployment under test.
        def probe = HttpClient.newHttpClient().send(
                HttpRequest.newBuilder(URI.create(sutUrl + sutPath + '/collections/' + sutCollection))
                        .header('Accept', 'application/json')
                        .GET()
                        .build(),
                BodyHandlers.ofString())
        if (probe.statusCode() == 200) {
            def meta = new JsonSlurper().parseText(probe.body())
            putCreates = (meta?.supportsNonAutogeneratedResourceIds == true)
        }
    }

    def cleanup() {
        // Tear down the fresh-id resource after every iteration so create-side tests start
        // from a clean slate (e.g. the round-trip test must observe a 201, not a 204 left
        // over from the create test). No-op when no fresh id is configured. POST-creates
        // mode is not handled here — server-assigned ids aren't tracked across tests, so
        // those features must be cleaned up out-of-band.
        deleteFreshId()
    }

    def cleanupSpec() {
        // Belt-and-braces: also delete after the whole spec, in case a test threw before
        // cleanup ran. Idempotent — a 404 from an already-absent fresh id is fine.
        deleteFreshId()
    }

    void deleteFreshId() {
        if (sutFreshId == null) return
        try {
            send('DELETE', itemUrl(sutFreshId), null)
        } catch (Throwable ignored) {
            // best effort
        }
    }

    static byte[] loadBody(String path) {
        path == null ? null : new File(path).bytes
    }

    String itemsUrl() {
        sutUrl + sutPath + '/collections/' + sutCollection + '/items'
    }

    String itemUrl(String id) {
        itemsUrl() + '/' + id
    }

    HttpResponse<String> send(String method, String url, byte[] body, Map<String, String> extraHeaders = [:]) {
        def builder = HttpRequest.newBuilder(URI.create(url))
        if (body != null) {
            builder.header('Content-Type', GEOJSON_CONTENT_TYPE)
        }
        if (sutContentCrs != null && body != null) {
            builder.header('Content-Crs', sutContentCrs)
        }
        extraHeaders.each { k, v -> builder.header(k, v) }
        def publisher = body == null ? BodyPublishers.noBody() : BodyPublishers.ofByteArray(body)
        builder.method(method, publisher)
        httpClient.send(builder.build(), BodyHandlers.ofString())
    }

    HttpResponse<String> getJson(String url) {
        def req = HttpRequest.newBuilder(URI.create(url))
                .header('Accept', GEOJSON_CONTENT_TYPE)
                .GET()
                .build()
        httpClient.send(req, BodyHandlers.ofString())
    }

    /**
     * Issues a create against the right endpoint for this collection's mode. Returns null
     * (and the caller should skip) when the mode requires a fresh id that wasn't supplied.
     */
    HttpResponse<String> createWith(byte[] body) {
        if (putCreates) {
            if (sutFreshId == null) return null
            return send('PUT', itemUrl(sutFreshId), body)
        }
        return send('POST', itemsUrl(), body)
    }

    String replaceId() {
        sutReplaceId ?: probeIdFromBody()
    }

    @IgnoreIf({ instance.putCreates && instance.sutFreshId == null })
    def 'create with a GeoJSON Feature returns 201'() {
        // POST mode: server assigns the id and returns it in Location.
        // PUT-creates mode: PUT to SUT_FRESH_ID; 201 means the feature did not yet exist.
        // Tip: if you see 204 here, the fresh id wasn't fresh — pick another and rerun.
        when:
        def r = createWith(sutBody)

        then:
        r.statusCode() == 201
        r.headers().firstValue('Location').isPresent()
    }

    def 'PUT GeoJSON Feature at the body id returns 2xx (201 if the id did not exist, 204 on replace)'() {
        when:
        def r = send('PUT', itemUrl(replaceId()), sutBody)

        then:
        r.statusCode() == 201 || r.statusCode() == 204
    }

    def 'PATCH with application/geo+json is rejected with 415'() {
        // PATCH must use a JSON merge-patch content type; geo+json is not a valid PATCH body.
        when:
        def r = send('PATCH', itemUrl(replaceId()), sutBody)

        then:
        r.statusCode() == 415
    }

    def 'FeatureCollection-shape body is rejected with 400 (single-Feature only)'() {
        // Wrap the bare Feature body in a FeatureCollection so the endpoint sees a multi-feature
        // shape that the decoder must reject before attempting schema-level validation. We
        // route through whichever method the deployment uses to create features (or, in PUT-
        // creates mode without a fresh id, through PUT-replace — the rejection is body-shape
        // based and happens regardless of create/replace intent).
        given:
        byte[] wrapped = wrapInFeatureCollection(sutBody)
        String url = (putCreates && sutFreshId == null)
                ? itemUrl(replaceId())
                : (putCreates ? itemUrl(sutFreshId) : itemsUrl())
        String method = putCreates ? 'PUT' : 'POST'

        when:
        def r = send(method, url, wrapped)

        then:
        r.statusCode() == 400
    }

    @IgnoreIf({ instance.putCreates && instance.sutFreshId == null })
    def 'create → GET round-trip surfaces a Feature document'() {
        // Create the feature, then GET it back as GeoJSON and confirm the response is a Feature
        // document. We assert on shape rather than exact byte equality — the response is not
        // byte-round-trip with the input, but it must surface the values that were written.
        when:
        def create = createWith(sutBody)
        String location = create.headers().firstValue('Location').orElse(null)

        then:
        create.statusCode() == 201
        location != null

        when:
        def get = getJson(location)

        then:
        get.statusCode() == 200
        def doc = new JsonSlurper().parseText(get.body())
        doc.type == 'Feature'
    }

    // -----------------------------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------------------------

    String probeIdFromBody() {
        // Scrape the first "id": ... property out of the body so the PUT-replace spec has an
        // id to hit when SUT_ID isn't supplied. Handles both string- and numeric-valued ids.
        // Not a full parse; good enough for a smoke test.
        String text = new String(sutBody, 'UTF-8')
        def m = text =~ /"id"\s*:\s*(?:"([^"]+)"|(\d+))/
        if (m.find()) {
            return m.group(1) ?: m.group(2)
        }
        return 'unknown-id'
    }

    static byte[] wrapInFeatureCollection(byte[] body) {
        String inner = new String(body, 'UTF-8').trim()
        // Parse + re-emit so the wrapper is structurally valid JSON regardless of the body's
        // whitespace or top-level shape.
        def feature = new JsonSlurper().parseText(inner)
        String wrapped = JsonOutput.toJson([type: 'FeatureCollection', features: [feature]])
        wrapped.getBytes('UTF-8')
    }
}
