
maturity = 'PROPOSAL'
maintenance = 'NONE'
description = 'Profiles for the reference system of the positions in the response.'
descriptionDe = 'Profile für das Referenzsystem der Positionen in der Antwort.'


dependencies {
    provided 'de.interactive_instruments:xtraplatform-crs'
    provided 'de.interactive_instruments:xtraplatform-features'
    provided 'de.interactive_instruments:ogcapi-features-core'
}
