
maturity = 'PROPOSAL'
maintenance = 'LOW'
description = 'Sort features in a response.'
descriptionDe = 'Sortieren von Features in Rückgaben.'


dependencies {
    provided 'de.interactive_instruments:xtraplatform-auth'
    provided 'de.interactive_instruments:xtraplatform-codelists'
    provided 'de.interactive_instruments:xtraplatform-features'
    provided 'de.interactive_instruments:xtraplatform-jsonschema'
    provided 'de.interactive_instruments:xtraplatform-web'
    provided 'de.interactive_instruments:ogcapi-collections'
    provided 'de.interactive_instruments:ogcapi-collections-queryables'
    provided 'de.interactive_instruments:ogcapi-common'
    provided 'de.interactive_instruments:ogcapi-features-core'

    testProvided 'de.interactive_instruments:xtraplatform-cql'
    testProvided 'de.interactive_instruments:xtraplatform-crs'
    testProvided 'de.interactive_instruments:xtraplatform-geometries'
}