when:
  event: pull_request

steps:

  code:
    image: eclipse-temurin:21@sha256:e58e492628c1428ceb838afc1a1b8762673d5eaa09296f560c363daea0fdcf3b
    environment:
      - DOCS_VERSION=next
    commands:
      - ./gradlew check docsVuepress -Pbranch=$CI_COMMIT_BRANCH -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]

  docs:
    image: woodpeckerci/plugin-surge-preview:1.2.2@sha256:7774113b37e1ae71406b427761003a6c5e5b6fe8c08ce7e06bb060f7201fd34f
    settings:
      path: build/markdown/docs/.vuepress/dist/
      surge_token: 
        from_secret: surge_token
      forge_type: github
      forge_url: https://github.com
      forge_repo_token: 
        from_secret: github_token
