when:
  event: pull_request

steps:

  code:
    image: eclipse-temurin:25@sha256:c2b7ea21649875fb9052237ac4e3cd4ef63968a2a389a0a1b1a72a5e53e5c93f
    environment:
      - DOCS_VERSION=next
    commands:
      - ./gradlew check docsVuepress -Pbranch=$CI_COMMIT_BRANCH -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]

  docs:
    image: woodpeckerci/plugin-surge-preview:1.4.2@sha256:85e52966e92030f4b45841176302909aefd0d8cf41cda90ae3c7209085f0cdc1
    settings:
      path: build/markdown/docs/.vuepress/dist/
      surge_token: 
        from_secret: surge_token
      forge_type: github
      forge_url: https://github.com
      forge_repo_token: 
        from_secret: github_token
