when:
  event: pull_request

steps:

  code:
    image: eclipse-temurin:25@sha256:119a3d18f160a3e7655a66034d0f43beee31cd7b3b9142d57a5de29772011de6
    environment:
      - DOCS_VERSION=next
    commands:
      - ./gradlew check docsVuepress -Pbranch=$CI_COMMIT_BRANCH -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]

  docs:
    image: woodpeckerci/plugin-surge-preview:1.4.3@sha256:4863d468cd47a4780673ce2b666fe75cd872711a115092d9831df2d735cdfcdb
    settings:
      path: build/markdown/docs/.vuepress/dist/
      surge_token: 
        from_secret: surge_token
      forge_type: github
      forge_url: https://github.com
      forge_repo_token: 
        from_secret: github_token
