when:
  event: [ push ]
  branch: [ master, maintenance-* ]

steps:
  dtrack:
    image: eclipse-temurin:21@sha256:e58e492628c1428ceb838afc1a1b8762673d5eaa09296f560c363daea0fdcf3b
    commands:
      - ./gradlew publishSbom -PdtrackApiUrl=https://dtrack.ldproxy.net/api/v1/bom -PdtrackApiKey=$DTRACK_API_KEY
    secrets: [ dtrack_api_key ]

