when:
  event: [ push ]
  branch: [ master, maintenance-* ]

steps:
  dtrack:
    image: eclipse-temurin:17@sha256:a27c79d44326d5f689668df5fedfee487652066d2a91e172747056cc7fbee6fc
    commands:
      - ./gradlew publishSbom -PdtrackApiUrl=https://dtrack.ldproxy.net/api/v1/bom -PdtrackApiKey=$DTRACK_API_KEY
    secrets: [ dtrack_api_key ]

