when:
  event: [ push ]
  branch: [ master, maintenance-* ]

steps:
  dtrack:
    image: eclipse-temurin:25@sha256:e787e08ef76f4c16866108cd7f9fcd96a68eef3ac6cc76866897d4d02d5a2262
    commands:
      - ./gradlew publishSbom -PdtrackApiUrl=https://dtrack.ldproxy.net/api/v1/bom -PdtrackApiKey=$DTRACK_API_KEY
    secrets: [ dtrack_api_key ]

