
depends_on:
  - release

when:
  event: [ tag ]

steps:

  dtrack:
    image: eclipse-temurin:25@sha256:c2b7ea21649875fb9052237ac4e3cd4ef63968a2a389a0a1b1a72a5e53e5c93f
    commands:
      - ./gradlew publishSbom -Prelease=true -PdtrackApiUrl=https://dtrack.ldproxy.net/api/v1/bom -PdtrackApiKey=$DTRACK_API_KEY
    secrets: [ dtrack_api_key ]

  github:
    image: meltwaterfoundation/github-cli:2.37.0@sha256:9b0e59b7a9b92188376121abce74604f70b9942f79ff4badf776910121f4519c
    commands:
      - gh release upload $CI_COMMIT_TAG "build/reports/sbom.json#CycloneDX SBOM"
    secrets: [ github_token ]

